feat: comment run all test

diff --git a/.github/workflows/ci_module.yml b/.github/workflows/ci_module.yml
--- a/.github/workflows/ci_module.yml
+++ b/.github/workflows/ci_module.yml
@@ -260,101 +260,101 @@ jobs:
           OPENSEARCH_PASSWORD: B9wc9VrqX7pY
           OPEN_SEARCH_HTTP_PORT: 9200
           OPENSEARCH_HOSTS: "localhost:9200"
-  ci_module_psql_test:
-    name: Run All Tests (PSQL)
-    runs-on: ubuntu-24.04
-    needs: build_backend
-    services:
-      pgsql:
-        image: ghcr.io/openimis/openimis-pgsql:develop
-        env:
-          DB_HOST: localhost
-          DB_PORT: 5432
-          POSTGRES_DB: test_imis
-          POSTGRES_USER: postgres
-          POSTGRES_PASSWORD: YourStrong!Passw0rd
-        ports:
-          - 5432:5432
-        options: >-
-          --health-cmd pg_isready
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 10
-    steps:
-      - name: Set up Python 3.11
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.11'
+  # ci_module_psql_test:
+  #   name: Run All Tests (PSQL)
+  #   runs-on: ubuntu-24.04
+  #   needs: build_backend
+  #   services:
+  #     pgsql:
+  #       image: ghcr.io/openimis/openimis-pgsql:develop
+  #       env:
+  #         DB_HOST: localhost
+  #         DB_PORT: 5432
+  #         POSTGRES_DB: test_imis
+  #         POSTGRES_USER: postgres
+  #         POSTGRES_PASSWORD: YourStrong!Passw0rd
+  #       ports:
+  #         - 5432:5432
+  #       options: >-
+  #         --health-cmd pg_isready
+  #         --health-interval 10s
+  #         --health-timeout 5s
+  #         --health-retries 10
+  #   steps:
+  #     - name: Set up Python 3.11
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: '3.11'
 
-      - name: Download site-packages artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: site-packages
-          path: /tmp/
+  #     - name: Download site-packages artifact
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: site-packages
+  #         path: /tmp/
 
-      - name: Locate site-packages
-        run: |
-          SITE_PACKAGES=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
-          echo "SITE_PACKAGES=$SITE_PACKAGES" >> $GITHUB_ENV
+  #     - name: Locate site-packages
+  #       run: |
+  #         SITE_PACKAGES=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
+  #         echo "SITE_PACKAGES=$SITE_PACKAGES" >> $GITHUB_ENV
 
-      - name: Download site-packages artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: code-artifacts
-          path: /tmp/
+  #     - name: Download site-packages artifact
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: code-artifacts
+  #         path: /tmp/
 
-      - name: Decompress artifacts
-        run: |
-          sudo tar -xzf /tmp/site-packages.tar.gz -C ${{ env.SITE_PACKAGES }}
-          sudo tar -xzf /tmp/openimis.tar.gz -C .
-      - name: Initialize PSQL
-        run: |
-          if [ ${GITHUB_REF##*/} = "main" ]; then export DBBRANCH="main"; else export DBBRANCH="develop"; fi
-          echo "Branch ${GITHUB_REF##*/}, usign ${DBBRANCH} branch for database"
-          git clone  --depth=1 --branch=$DBBRANCH https://github.com/openimis/database_postgresql.git ./sql_psql
-          sudo bash ./sql_psql/install_postgres_json_schema_extension.sh
-          echo 'set search_path to public' >> ~/.psqlrc
-          PGPASSWORD=YourStrong!Passw0rd psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/json_schema_extension.sql | grep . | uniq -c
-        env:
-          DB_HOST: localhost
-          DB_PORT: 5432
-          DB_NAME: test_imis
-          DB_TEST_NAME: test_imis
-          DB_USER: postgres
-          DB_PASSWORD: YourStrong!Passw0rd
+  #     - name: Decompress artifacts
+  #       run: |
+  #         sudo tar -xzf /tmp/site-packages.tar.gz -C ${{ env.SITE_PACKAGES }}
+  #         sudo tar -xzf /tmp/openimis.tar.gz -C .
+  #     - name: Initialize PSQL
+  #       run: |
+  #         if [ ${GITHUB_REF##*/} = "main" ]; then export DBBRANCH="main"; else export DBBRANCH="develop"; fi
+  #         echo "Branch ${GITHUB_REF##*/}, usign ${DBBRANCH} branch for database"
+  #         git clone  --depth=1 --branch=$DBBRANCH https://github.com/openimis/database_postgresql.git ./sql_psql
+  #         sudo bash ./sql_psql/install_postgres_json_schema_extension.sh
+  #         echo 'set search_path to public' >> ~/.psqlrc
+  #         PGPASSWORD=YourStrong!Passw0rd psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/json_schema_extension.sql | grep . | uniq -c
+  #       env:
+  #         DB_HOST: localhost
+  #         DB_PORT: 5432
+  #         DB_NAME: test_imis
+  #         DB_TEST_NAME: test_imis
+  #         DB_USER: postgres
+  #         DB_PASSWORD: YourStrong!Passw0rd
       
       
-      - name: Django tests PSQL
-        working-directory: ./openimis/openIMIS
-        # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
-        if: success() || failure()
-        run: |
-          python -V
-          export MODULES=$(jq -r '(.modules[].name)' ../openimis.json | xargs)
-          MODULES=$(echo "$MODULES" | sed -E "s/\b$(echo "${CI_EXCLUDED_MODULE// /\\b|\\b}")\b/ /g" | xargs)
-          echo $MODULES
-          python manage.py test --keepdb $MODULES
-        env:
-          SECRET_KEY: secret
-          MODE: DEV
-          DB_DEFAULT: postgresql
-          CELERY_BROKER_URL: "memory://openIMIS-test//"
-          CELERY_RESULT_BACKEND: "cache+memory://openIMIS-test//"
-          #DJANGO_SETTINGS_MODULE: hat.settings
-          DB_HOST: localhost
-          DB_PORT: 5432
-          DB_NAME: test_imis
-          DB_TEST_NAME: test_imis
-          DB_USER: postgres
-          DB_PASSWORD: YourStrong!Passw0rd
-          #DEV_SERVER: true
-          SITE_ROOT: api
-          CI_EXCLUDED_MODULE: ${{ vars.CI_EXCLUDED_MODULE }}
-          OPENSEARCH_ADMIN: admin
-          OPENSEARCH_PASSWORD: B9wc9VrqX7pY
-          OPEN_SEARCH_HTTP_PORT: 9200
-          OPENSEARCH_HOSTS: "localhost:9200"
-          OPENSEARCH_DSL_AUTOSYNC: False
+  #     - name: Django tests PSQL
+  #       working-directory: ./openimis/openIMIS
+  #       # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
+  #       if: success() || failure()
+  #       run: |
+  #         python -V
+  #         export MODULES=$(jq -r '(.modules[].name)' ../openimis.json | xargs)
+  #         MODULES=$(echo "$MODULES" | sed -E "s/\b$(echo "${CI_EXCLUDED_MODULE// /\\b|\\b}")\b/ /g" | xargs)
+  #         echo $MODULES
+  #         python manage.py test --keepdb $MODULES
+  #       env:
+  #         SECRET_KEY: secret
+  #         MODE: DEV
+  #         DB_DEFAULT: postgresql
+  #         CELERY_BROKER_URL: "memory://openIMIS-test//"
+  #         CELERY_RESULT_BACKEND: "cache+memory://openIMIS-test//"
+  #         #DJANGO_SETTINGS_MODULE: hat.settings
+  #         DB_HOST: localhost
+  #         DB_PORT: 5432
+  #         DB_NAME: test_imis
+  #         DB_TEST_NAME: test_imis
+  #         DB_USER: postgres
+  #         DB_PASSWORD: YourStrong!Passw0rd
+  #         #DEV_SERVER: true
+  #         SITE_ROOT: api
+  #         CI_EXCLUDED_MODULE: ${{ vars.CI_EXCLUDED_MODULE }}
+  #         OPENSEARCH_ADMIN: admin
+  #         OPENSEARCH_PASSWORD: B9wc9VrqX7pY
+  #         OPEN_SEARCH_HTTP_PORT: 9200
+  #         OPENSEARCH_HOSTS: "localhost:9200"
+  #         OPENSEARCH_DSL_AUTOSYNC: False
       # - name: Generate Coverage Report
       #   if: always()
       #   working-directory: ./openimis/openIMIS
