feat: comment mmsql tests

diff --git a/.github/workflows/ci_module.yml b/.github/workflows/ci_module.yml
--- a/.github/workflows/ci_module.yml
+++ b/.github/workflows/ci_module.yml
@@ -121,131 +121,131 @@ jobs:
         with:
           name: code-artifacts
           path: openimis.tar.gz
-  ci_module_mssql_tests:
-    name: Run All Tests (MSSQL)
-    runs-on: ubuntu-24.04
-    needs: build_backend
-    services:
-      mssql:
-        image: mcr.microsoft.com/mssql/server:2017-latest
-        env:
-          ACCEPT_EULA: Y
-          SA_PASSWORD: GitHub999
-        ports:
-          - 1433:1433
-        # this health-cmd needed because the mssql container does not provide a health check
-        options: >-
-          --health-interval=10s
-          --health-timeout=5s
-          --health-start-period=10s
-          --health-retries=10
-          --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1"
-    steps:
-      - name: Set up Python 3.10
-        uses: actions/setup-python@v5
-        with:
-          python-version: "3.10"
+  # ci_module_mssql_tests:
+  #   name: Run All Tests (MSSQL)
+  #   runs-on: ubuntu-24.04
+  #   needs: build_backend
+  #   services:
+  #     mssql:
+  #       image: mcr.microsoft.com/mssql/server:2017-latest
+  #       env:
+  #         ACCEPT_EULA: Y
+  #         SA_PASSWORD: GitHub999
+  #       ports:
+  #         - 1433:1433
+  #       # this health-cmd needed because the mssql container does not provide a health check
+  #       options: >-
+  #         --health-interval=10s
+  #         --health-timeout=5s
+  #         --health-start-period=10s
+  #         --health-retries=10
+  #         --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1"
+  #   steps:
+  #     - name: Set up Python 3.10
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: "3.10"
 
-      - name: Download site-packages artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: site-packages
-          path: /tmp/
+  #     - name: Download site-packages artifact
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: site-packages
+  #         path: /tmp/
 
 
-      - name: Locate site-packages
-        run: |
-          SITE_PACKAGES=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
-          echo "SITE_PACKAGES=$SITE_PACKAGES" >> $GITHUB_ENV
-          #export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^openimis/openimis-be-\(.*\)_py$#\1#')"
-          # pour gérer à la fois les dépôts openimis et les forks
-          export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^\(.*\)/openimis-be-\(.*\)_py$#\1#')"
-          echo "MODULE_NAME=$MODULE_NAME" >> $GITHUB_ENV
+  #     - name: Locate site-packages
+  #       run: |
+  #         SITE_PACKAGES=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
+  #         echo "SITE_PACKAGES=$SITE_PACKAGES" >> $GITHUB_ENV
+  #         #export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^openimis/openimis-be-\(.*\)_py$#\1#')"
+  #         # pour gérer à la fois les dépôts openimis et les forks
+  #         export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^\(.*\)/openimis-be-\(.*\)_py$#\1#')"
+  #         echo "MODULE_NAME=$MODULE_NAME" >> $GITHUB_ENV
 
-          # Extraire le nom du module depuis le dépôt (fork ou officiel)
-          MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^\(.*\)/openimis-be-\(.*\)_py$#\2#')"
-          echo "MODULE_NAME=$MODULE_NAME" >> $GITHUB_ENV
+  #         # Extraire le nom du module depuis le dépôt (fork ou officiel)
+  #         MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^\(.*\)/openimis-be-\(.*\)_py$#\2#')"
+  #         echo "MODULE_NAME=$MODULE_NAME" >> $GITHUB_ENV
 
-          # Extraire le nom de la branche (sans refs/heads/)
-          BRANCH_NAME="${GITHUB_REF##*/}"
-          echo "BRANCH_NAME=$BRANCH_NAME"
+  #         # Extraire le nom de la branche (sans refs/heads/)
+  #         BRANCH_NAME="${GITHUB_REF##*/}"
+  #         echo "BRANCH_NAME=$BRANCH_NAME"
 
-          # Impression dans les logs pour débogage
-          echo "Detected module: $MODULE_NAME"
-          echo "Detected branch: $BRANCH_NAME"
+  #         # Impression dans les logs pour débogage
+  #         echo "Detected module: $MODULE_NAME"
+  #         echo "Detected branch: $BRANCH_NAME"
 
-      - name: Download site-packages artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: code-artifacts
-          path: /tmp/
+  #     - name: Download site-packages artifact
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: code-artifacts
+  #         path: /tmp/
 
-      - name: Decompress artifacts
-        run: |
-          sudo tar -xzf /tmp/site-packages.tar.gz -C ${{ env.SITE_PACKAGES }}
-          sudo tar -xzf /tmp/openimis.tar.gz -C .
-      - name: Initialize MSSQL
-        run: |
-          export DB_NAME_TEST="test_$DB_NAME"
+  #     - name: Decompress artifacts
+  #       run: |
+  #         sudo tar -xzf /tmp/site-packages.tar.gz -C ${{ env.SITE_PACKAGES }}
+  #         sudo tar -xzf /tmp/openimis.tar.gz -C .
+  #     - name: Initialize MSSQL
+  #       run: |
+  #         export DB_NAME_TEST="test_$DB_NAME"
           
-          if [ ${GITHUB_REF##*/} = "main" ]; then export DBBRANCH="main"; else export DBBRANCH="develop"; fi
-          echo "Branch ${GITHUB_REF##*/}, usign ${DBBRANCH} branch for database"
-          git clone --depth=1 --branch=$DBBRANCH https://github.com/openimis/database_ms_sqlserver.git ./sql_mssql
-          cd sql_mssql/ && bash script/concatenate_files.sh && cd ..
+  #         if [ ${GITHUB_REF##*/} = "main" ]; then export DBBRANCH="main"; else export DBBRANCH="develop"; fi
+  #         echo "Branch ${GITHUB_REF##*/}, usign ${DBBRANCH} branch for database"
+  #         git clone --depth=1 --branch=$DBBRANCH https://github.com/openimis/database_ms_sqlserver.git ./sql_mssql
+  #         cd sql_mssql/ && bash script/concatenate_files.sh && cd ..
 
-          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
-          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
-          sudo apt-get update
-          sudo apt-get install mssql-tools unixodbc-dev
+  #         curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
+  #         curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
+  #         sudo apt-get update
+  #         sudo apt-get install mssql-tools unixodbc-dev
           
-          #Main db has to exists for tests to run correctly, psql container creates empty main db by default
-          /opt/mssql-tools/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "DROP DATABASE IF EXISTS $DB_NAME"
-          /opt/mssql-tools/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "CREATE DATABASE $DB_NAME"
+  #         #Main db has to exists for tests to run correctly, psql container creates empty main db by default
+  #         /opt/mssql-tools/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "DROP DATABASE IF EXISTS $DB_NAME"
+  #         /opt/mssql-tools/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "CREATE DATABASE $DB_NAME"
 
-          /opt/mssql-tools/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "DROP DATABASE IF EXISTS $DB_NAME_TEST"
-          /opt/mssql-tools/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "CREATE DATABASE $DB_NAME_TEST"
-          /opt/mssql-tools/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -d $DB_NAME_TEST -i ./sql_mssql/output/fullDemoDatabase.sql | grep . | uniq -c
-          /opt/mssql-tools/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -d $DB_NAME -i ./sql_mssql/output/fullDemoDatabase.sql | grep . | uniq -c
+  #         /opt/mssql-tools/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "DROP DATABASE IF EXISTS $DB_NAME_TEST"
+  #         /opt/mssql-tools/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "CREATE DATABASE $DB_NAME_TEST"
+  #         /opt/mssql-tools/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -d $DB_NAME_TEST -i ./sql_mssql/output/fullDemoDatabase.sql | grep . | uniq -c
+  #         /opt/mssql-tools/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -d $DB_NAME -i ./sql_mssql/output/fullDemoDatabase.sql | grep . | uniq -c
 
-        env:
-          DB_HOST: localhost
-          DB_PORT: 1433
-          DB_NAME: imis
-          DB_USER: sa
-          DB_PASSWORD: GitHub999
-      - name: Cache dependencies
-        uses: actions/cache@v4
-        with:
-          path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
-          restore-keys: |
-            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
-            ${{ runner.os }}-pip-
-            ${{ runner.os }}-
-      - name: Django tests MSSQL
-        working-directory: ./openimis/openIMIS
-        # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
-        if: success() || failure()
-        run: |
-          python -V
-          #python manage.py migrate
-          #python manage.py test --debug-mode --timing --keepdb $MODULE_NAME
-          #DJANGO_SETTINGS_MODULE=openIMIS.settings python -Wd -X dev -m coverage run --source=$MODULE_NAME manage.py test --debug-mode --timing --keepdb $MODULE_NAME
-        env:
-          SECRET_KEY: secret
-          MODE: DEV
-          DB_ENGINE: mssql
-          #DJANGO_SETTINGS_MODULE: hat.settings
-          DB_HOST: localhost
-          DB_PORT: 1433
-          DB_NAME: imis
-          DB_USER: sa
-          DB_PASSWORD: GitHub999
-          PASSWORD_MIN_LENGTH: 8
-          #DEV_SERVER: true
-          SITE_ROOT: api
-          #REMOTE_USER_AUTHENTICATION: False
-          CI_EXCLUDED_MODULE: ${{ vars.CI_EXCLUDED_MODULE }}
+  #       env:
+  #         DB_HOST: localhost
+  #         DB_PORT: 1433
+  #         DB_NAME: imis
+  #         DB_USER: sa
+  #         DB_PASSWORD: GitHub999
+  #     - name: Cache dependencies
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ~/.cache/pip
+  #         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
+  #         restore-keys: |
+  #           ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
+  #           ${{ runner.os }}-pip-
+  #           ${{ runner.os }}-
+  #     - name: Django tests MSSQL
+  #       working-directory: ./openimis/openIMIS
+  #       # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
+  #       if: success() || failure()
+  #       run: |
+  #         python -V
+  #         python manage.py migrate
+  #         python manage.py test --debug-mode --timing --keepdb $MODULE_NAME
+  #         #DJANGO_SETTINGS_MODULE=openIMIS.settings python -Wd -X dev -m coverage run --source=$MODULE_NAME manage.py test --debug-mode --timing --keepdb $MODULE_NAME
+  #       env:
+  #         SECRET_KEY: secret
+  #         MODE: DEV
+  #         DB_ENGINE: mssql
+  #         #DJANGO_SETTINGS_MODULE: hat.settings
+  #         DB_HOST: localhost
+  #         DB_PORT: 1433
+  #         DB_NAME: imis
+  #         DB_USER: sa
+  #         DB_PASSWORD: GitHub999
+  #         PASSWORD_MIN_LENGTH: 8
+  #         #DEV_SERVER: true
+  #         SITE_ROOT: api
+  #         #REMOTE_USER_AUTHENTICATION: False
+  #         CI_EXCLUDED_MODULE: ${{ vars.CI_EXCLUDED_MODULE }}
   ci_module_psql_test:
     name: Run All Tests (PSQL)
     runs-on: ubuntu-24.04
