Fix: comment psql tests

diff --git a/.github/workflows/ci_module.yml b/.github/workflows/ci_module.yml
--- a/.github/workflows/ci_module.yml
+++ b/.github/workflows/ci_module.yml
@@ -243,155 +243,155 @@ jobs:
           SITE_ROOT: api
           #REMOTE_USER_AUTHENTICATION: False
           CI_EXCLUDED_MODULE: ${{ vars.CI_EXCLUDED_MODULE }}
-  ci_module_psql_test:
-    name: Run All Tests (PSQL)
-    runs-on: ubuntu-24.04
-    needs: build_backend
-    services:
-      pgsql:
-        image: postgres
-        env:
-          DB_HOST: localhost
-          DB_PORT: 5432
-          POSTGRES_DB: imis
-          POSTGRES_USER: postgres
-          POSTGRES_PASSWORD: GitHub999
-        ports:
-          - 5432:5432
-        options: >-
-          --health-cmd pg_isready
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 10
-    steps:
-      - name: Set up Python 3.10
-        uses: actions/setup-python@v5
-        with:
-          python-version: "3.10"
+  # ci_module_psql_test:
+  #   name: Run All Tests (PSQL)
+  #   runs-on: ubuntu-24.04
+  #   needs: build_backend
+  #   services:
+  #     pgsql:
+  #       image: postgres
+  #       env:
+  #         DB_HOST: localhost
+  #         DB_PORT: 5432
+  #         POSTGRES_DB: imis
+  #         POSTGRES_USER: postgres
+  #         POSTGRES_PASSWORD: GitHub999
+  #       ports:
+  #         - 5432:5432
+  #       options: >-
+  #         --health-cmd pg_isready
+  #         --health-interval 10s
+  #         --health-timeout 5s
+  #         --health-retries 10
+  #   steps:
+  #     - name: Set up Python 3.10
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: "3.10"
 
-      - name: Download site-packages artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: site-packages
-          path: /tmp/
+  #     - name: Download site-packages artifact
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: site-packages
+  #         path: /tmp/
 
-      - name: Locate site-packages
-        run: |
-          SITE_PACKAGES=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
-          echo "SITE_PACKAGES=$SITE_PACKAGES" >> $GITHUB_ENV
-          #export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^openimis/openimis-be-\(.*\)_py$#\1#')"
-          # pour gérer à la fois les dépôts openimis et les forks
-          export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^\(.*\)/openimis-be-\(.*\)_py$#\1#')"
-          echo "MODULE_NAME=$MODULE_NAME" >> $GITHUB_ENV
+  #     - name: Locate site-packages
+  #       run: |
+  #         SITE_PACKAGES=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
+  #         echo "SITE_PACKAGES=$SITE_PACKAGES" >> $GITHUB_ENV
+  #         #export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^openimis/openimis-be-\(.*\)_py$#\1#')"
+  #         # pour gérer à la fois les dépôts openimis et les forks
+  #         export MODULE_NAME="$(echo $GITHUB_REPOSITORY | sed 's#^\(.*\)/openimis-be-\(.*\)_py$#\1#')"
+  #         echo "MODULE_NAME=$MODULE_NAME" >> $GITHUB_ENV
 
-      - name: Download site-packages artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: code-artifacts
-          path: /tmp/
+  #     - name: Download site-packages artifact
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: code-artifacts
+  #         path: /tmp/
 
-      - name: Decompress artifacts
-        run: |
-          sudo tar -xzf /tmp/site-packages.tar.gz -C ${{ env.SITE_PACKAGES }}
-          sudo tar -xzf /tmp/openimis.tar.gz -C .
-      - name: Initialize PSQL
-        run: |
-          export DB_NAME_TEST="test_$DB_NAME"
+  #     - name: Decompress artifacts
+  #       run: |
+  #         sudo tar -xzf /tmp/site-packages.tar.gz -C ${{ env.SITE_PACKAGES }}
+  #         sudo tar -xzf /tmp/openimis.tar.gz -C .
+  #     - name: Initialize PSQL
+  #       run: |
+  #         export DB_NAME_TEST="test_$DB_NAME"
           
-          if [ ${GITHUB_REF##*/} = "main" ]; then export DBBRANCH="main"; else export DBBRANCH="develop"; fi
-          echo "Branch ${GITHUB_REF##*/}, usign ${DBBRANCH} branch for database"
-          git clone  --depth=1 --branch=$DBBRANCH https://github.com/openimis/database_postgresql.git ./sql_psql
+  #         if [ ${GITHUB_REF##*/} = "main" ]; then export DBBRANCH="main"; else export DBBRANCH="develop"; fi
+  #         echo "Branch ${GITHUB_REF##*/}, usign ${DBBRANCH} branch for database"
+  #         git clone  --depth=1 --branch=$DBBRANCH https://github.com/openimis/database_postgresql.git ./sql_psql
           
-          echo 'set search_path to public' >> ~/.psqlrc
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -c "DROP DATABASE IF EXISTS \"$DB_NAME_TEST\";"
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -c "CREATE DATABASE \"$DB_NAME_TEST\";"
+  #         echo 'set search_path to public' >> ~/.psqlrc
+  #         PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -c "DROP DATABASE IF EXISTS \"$DB_NAME_TEST\";"
+  #         PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -c "CREATE DATABASE \"$DB_NAME_TEST\";"
           
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/00_dump.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/02_aux_functions.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/03_views.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/04_functions.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/05_stored_procs.sql | grep . | uniq -c
-          PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/demo_db.sql | grep . | uniq -c
+  #         PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/00_dump.sql | grep . | uniq -c
+  #         PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/02_aux_functions.sql | grep . | uniq -c
+  #         PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/03_views.sql | grep . | uniq -c
+  #         PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/04_functions.sql | grep . | uniq -c
+  #         PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/05_stored_procs.sql | grep . | uniq -c
+  #         PGPASSWORD=GitHub999 psql -U $DB_USER -h $DB_HOST -d $DB_NAME_TEST -f  ./sql_psql/database\ scripts/demo_db.sql | grep . | uniq -c
 
-        env:
-          DB_HOST: localhost
-          DB_PORT: 5432
-          DB_NAME: imis
-          DB_USER: postgres
-          DB_PASSWORD: GitHub999
-      - name: Django tests PSQL
-        working-directory: ./openimis/openIMIS
-        id: django-test-psql
-        # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
-        if: success() || failure()
-        run: |
-          python -V
-          # This has to exit 0, or report is not generated 
-          python -m coverage run --source=$MODULE_NAME --omit=*/migrations/* ./manage.py test --keepdb $MODULE_NAME
-        env:
-          SECRET_KEY: secret
-          MODE: DEV
-          DB_ENGINE: django.db.backends.postgresql
-          #DJANGO_SETTINGS_MODULE: hat.settings
-          DB_HOST: localhost
-          DB_PORT: 5432
-          DB_NAME: imis
-          DB_USER: postgres
-          DB_PASSWORD: GitHub999
-          #DEV_SERVER: true
-          SITE_ROOT: api
-          CI_EXCLUDED_MODULE: ${{ vars.CI_EXCLUDED_MODULE }}
-      - name: Django full PSQL
-        working-directory: ./openimis/openIMIS
-        id: django-full-psql
-        # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
-        run: |
-          export MODULES=$(jq -r '(.modules[].name)' ../openimis.json | xargs)
-          # Remove some module from MODULES
-          MODULES=$(echo "$MODULES" | sed -E "s/\b$(echo "${CI_EXCLUDED_MODULE// /\\b|\\b}")\b/ /g" | xargs)
-          echo "MODULES=$MODULES" >> $GITHUB_ENV  
-          python manage.py test --debug-mode --timing --keepdb $MODULES
-        continue-on-error: true
-        env:
-          SECRET_KEY: secret
-          MODE: DEV
-          DB_ENGINE: django.db.backends.postgresql
-          #DJANGO_SETTINGS_MODULE: hat.settings
-          DB_HOST: localhost
-          DB_PORT: 5432
-          DB_NAME: imis
-          DB_USER: postgres
-          DB_PASSWORD: GitHub999
-          #DEV_SERVER: true
-          SITE_ROOT: api
-          CI_EXCLUDED_MODULE: ${{ vars.CI_EXCLUDED_MODULE }}
-      # Check if the full test failed but not the PSQL
-      - name: Set warning status if full test step failed
-        id: check-status
-        run: echo "status=${{ steps.django-full-psql.outcome == 'failure' && steps.django-test-psql.outcome == 'success' }}" >> $GITHUB_OUTPUT
-      # Print a warning message if the previous step failed
-      - name: Print warning
-        if: steps.check-status.outputs.status == 'true'
-        run: echo "::warning::Global test failed, check if it is not because of your changes"
-      - name: Generate Coverage Report
-        if: always()
-        working-directory: ./openimis/openIMIS
-        run: |
-          python -m coverage xml -o coverage.xml
-          # Only leave actual code part, skip absuolute directory like 
-          # /home/runner/work/openimis-be-invoice_py/openimis-be-invoice_py/current-module/
-          # It's required by circle-ci setup
-          mkdir coverage
-          sed -E 's|/home/runner/work/(.*?)/(.*?)/current-module/|./current-module/|' coverage.xml >> coverage/coverage1.xml
-          sed -E 's|/home/runner/work/(.*?)/(.*?)/current-module/|./|' coverage.xml >> coverage/coverage2.xml
+  #       env:
+  #         DB_HOST: localhost
+  #         DB_PORT: 5432
+  #         DB_NAME: imis
+  #         DB_USER: postgres
+  #         DB_PASSWORD: GitHub999
+  #     - name: Django tests PSQL
+  #       working-directory: ./openimis/openIMIS
+  #       id: django-test-psql
+  #       # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
+  #       if: success() || failure()
+  #       run: |
+  #         python -V
+  #         # This has to exit 0, or report is not generated 
+  #         python -m coverage run --source=$MODULE_NAME --omit=*/migrations/* ./manage.py test --keepdb $MODULE_NAME
+  #       env:
+  #         SECRET_KEY: secret
+  #         MODE: DEV
+  #         DB_ENGINE: django.db.backends.postgresql
+  #         #DJANGO_SETTINGS_MODULE: hat.settings
+  #         DB_HOST: localhost
+  #         DB_PORT: 5432
+  #         DB_NAME: imis
+  #         DB_USER: postgres
+  #         DB_PASSWORD: GitHub999
+  #         #DEV_SERVER: true
+  #         SITE_ROOT: api
+  #         CI_EXCLUDED_MODULE: ${{ vars.CI_EXCLUDED_MODULE }}
+  #     - name: Django full PSQL
+  #       working-directory: ./openimis/openIMIS
+  #       id: django-full-psql
+  #       # Run the tests regardless if previous steps failed (if setup fails the tests should crash instantly)
+  #       run: |
+  #         export MODULES=$(jq -r '(.modules[].name)' ../openimis.json | xargs)
+  #         # Remove some module from MODULES
+  #         MODULES=$(echo "$MODULES" | sed -E "s/\b$(echo "${CI_EXCLUDED_MODULE// /\\b|\\b}")\b/ /g" | xargs)
+  #         echo "MODULES=$MODULES" >> $GITHUB_ENV  
+  #         python manage.py test --debug-mode --timing --keepdb $MODULES
+  #       continue-on-error: true
+  #       env:
+  #         SECRET_KEY: secret
+  #         MODE: DEV
+  #         DB_ENGINE: django.db.backends.postgresql
+  #         #DJANGO_SETTINGS_MODULE: hat.settings
+  #         DB_HOST: localhost
+  #         DB_PORT: 5432
+  #         DB_NAME: imis
+  #         DB_USER: postgres
+  #         DB_PASSWORD: GitHub999
+  #         #DEV_SERVER: true
+  #         SITE_ROOT: api
+  #         CI_EXCLUDED_MODULE: ${{ vars.CI_EXCLUDED_MODULE }}
+  #     # Check if the full test failed but not the PSQL
+  #     - name: Set warning status if full test step failed
+  #       id: check-status
+  #       run: echo "status=${{ steps.django-full-psql.outcome == 'failure' && steps.django-test-psql.outcome == 'success' }}" >> $GITHUB_OUTPUT
+  #     # Print a warning message if the previous step failed
+  #     - name: Print warning
+  #       if: steps.check-status.outputs.status == 'true'
+  #       run: echo "::warning::Global test failed, check if it is not because of your changes"
+  #     - name: Generate Coverage Report
+  #       if: always()
+  #       working-directory: ./openimis/openIMIS
+  #       run: |
+  #         python -m coverage xml -o coverage.xml
+  #         # Only leave actual code part, skip absuolute directory like 
+  #         # /home/runner/work/openimis-be-invoice_py/openimis-be-invoice_py/current-module/
+  #         # It's required by circle-ci setup
+  #         mkdir coverage
+  #         sed -E 's|/home/runner/work/(.*?)/(.*?)/current-module/|./current-module/|' coverage.xml >> coverage/coverage1.xml
+  #         sed -E 's|/home/runner/work/(.*?)/(.*?)/current-module/|./|' coverage.xml >> coverage/coverage2.xml
           
-          cat coverage.xml
-      - name: Coverage results
-        if: success() || failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: coverage.xml
-          path: ./openimis/openIMIS/coverage
+  #         cat coverage.xml
+  #     - name: Coverage results
+  #       if: success() || failure()
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: coverage.xml
+  #         path: ./openimis/openIMIS/coverage
   flake-8-linter:
     continue-on-error: true
     name: Run flake8 check
